import sys
import re
import os
import time
import json
from PySide6.QtCore import Qt, QPoint, QTimer, QPropertyAnimation, QEasingCurve, QSize
from PySide6.QtGui import QImage, QPixmap, QPainter, QColor, QFont, QIcon
from PySide6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QFrame, QLabel, QLineEdit,
    QPushButton, QVBoxLayout, QHBoxLayout, QSlider, QTextEdit, QFileDialog, QSizePolicy
)

# Configuration File to persist chosen workspace directory
CONFIG_FILE = "simulator_config.json"

# ==============================================================================
# 1. UPGRADED ADAPTIVE LVGL C-ARRAY IMAGE ASSET PARSER
# ==============================================================================
class LVGLImageParser:
    """
    Parses LVGL C files generated by SquareLine Studio.
    Supports both LVGL v8 and v9 C structure definitions.
    Automatically detects interleaved vs. separated 3-byte pixel streams.
    """
    @staticmethod
    def parse_file(filepath):
        if not filepath or not os.path.exists(filepath):
            return None

        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()

            # Parse dimensions using an improved, nested-brace compatible regex
            w_match = re.search(r'\.w\s*=\s*(\d+)|\.header\.w\s*=\s*(\d+)', content)
            h_match = re.search(r'\.h\s*=\s*(\d+)|\.header\.h\s*=\s*(\d+)', content)
            
            width = None
            height = None
            if w_match:
                width = int(next(filter(None, w_match.groups())))
            if h_match:
                height = int(next(filter(None, h_match.groups())))

            # Fallback size deductions if the exporter omitted named initializers
            if width is None or height is None:
                if "clock" in filepath.lower():
                    width, height = 200, 200
                elif "gear" in filepath.lower():
                    width, height = 64, 64
                else:
                    width, height = 120, 120

            # Extract the raw hex array
            array_match = re.search(
                r'const\s+uint8_t\s+ui_img_\w+_(?:data|map)\[\]\s*=\s*\{([^}]+)\}', 
                content
            )
            if not array_match:
                array_match = re.search(
                    r'const\s+LV_ATTRIBUTE_MEM_ALIGN\s+uint8_t\s+\w+_(?:data|map)\[\]\s*=\s*\{([^}]+)\}', 
                    content
                )
            if not array_match:
                array_match = re.search(r'=\s*\{([^}]+)\}', content)

            if not array_match:
                return None

            raw_hex_data = array_match.group(1)
            hex_tokens = re.findall(r'0x[0-9a-fA-F]+', raw_hex_data)
            byte_data = bytes(int(token, 16) for token in hex_tokens)

            # Dynamically calculate bytes per pixel to determine correct layout
            total_pixels = width * height
            bytes_per_pixel = len(byte_data) // total_pixels

            decoded_bytes = bytearray(total_pixels * 4)

            if bytes_per_pixel == 3:
                # Statistical auto-detection for interleaved (v8) vs separate (v9) 3-byte format
                interleaved_alpha_matches = sum(1 for i in range(total_pixels) if byte_data[i * 3 + 2] in (0x00, 0xFF))
                separated_alpha_matches = sum(1 for i in range(total_pixels) if byte_data[total_pixels * 2 + i] in (0x00, 0xFF))
                
                is_interleaved = interleaved_alpha_matches > separated_alpha_matches

                if is_interleaved:
                    # Format: Interleaved RGB565 + Alpha
                    for i in range(total_pixels):
                        base_src = i * 3
                        b0 = byte_data[base_src]
                        b1 = byte_data[base_src + 1]
                        alpha = byte_data[base_src + 2]

                        val = b0 | (b1 << 8)
                        r = ((val >> 11) & 0x1F) * 255 // 31
                        g = ((val >> 5) & 0x3F) * 255 // 63
                        b = (val & 0x1F) * 255 // 31

                        base_dst = i * 4
                        decoded_bytes[base_dst] = b      # Blue
                        decoded_bytes[base_dst + 1] = g  # Green
                        decoded_bytes[base_dst + 2] = r  # Red
                        decoded_bytes[base_dst + 3] = alpha
                else:
                    # Format: RGB565 + 8-bit Alpha (Separate color and alpha arrays)
                    color_len = total_pixels * 2
                    for i in range(total_pixels):
                        b0 = byte_data[i * 2]
                        b1 = byte_data[i * 2 + 1]
                        alpha = byte_data[color_len + i]

                        val = b0 | (b1 << 8)
                        r = ((val >> 11) & 0x1F) * 255 // 31
                        g = ((val >> 5) & 0x3F) * 255 // 63
                        b = (val & 0x1F) * 255 // 31

                        base_dst = i * 4
                        decoded_bytes[base_dst] = b
                        decoded_bytes[base_dst + 1] = g
                        decoded_bytes[base_dst + 2] = r
                        decoded_bytes[base_dst + 3] = alpha

            elif bytes_per_pixel == 2:
                # Standard RGB565 (2 bytes, No Alpha)
                for i in range(total_pixels):
                    base_src = i * 2
                    b0 = byte_data[base_src]
                    b1 = byte_data[base_src + 1]

                    val = b0 | (b1 << 8)
                    r = ((val >> 11) & 0x1F) * 255 // 31
                    g = ((val >> 5) & 0x3F) * 255 // 63
                    b = (val & 0x1F) * 255 // 31

                    base_dst = i * 4
                    decoded_bytes[base_dst] = b
                    decoded_bytes[base_dst + 1] = g
                    decoded_bytes[base_dst + 2] = r
                    decoded_bytes[base_dst + 3] = 255

            elif bytes_per_pixel == 4:
                # ARGB8888 (4 bytes per pixel)
                for i in range(total_pixels):
                    base = i * 4
                    decoded_bytes[base] = byte_data[base + 3]      # Blue
                    decoded_bytes[base + 1] = byte_data[base + 2]  # Green
                    decoded_bytes[base + 2] = byte_data[base + 1]  # Red
                    decoded_bytes[base + 3] = byte_data[base]      # Alpha
            else:
                return None

            q_img = QImage(decoded_bytes, width, height, QImage.Format_ARGB32)
            return QPixmap.fromImage(q_img)

        except Exception as e:
            print(f"Error parsing asset {filepath}: {e}")
            return None


# ==============================================================================
# 2. DYNAMIC MAIN.C FILE PARSER
# ==============================================================================
class MainCParser:
    """
    Parses watch main.c files dynamically to extract active display layouts,
    aligned coordinates, tile counts, and interactive click event routing.
    """
    @staticmethod
    def parse_main_c(filepath):
        config = {
            "tiles": {},          # var_name -> index (e.g. 'tile_clock' -> 0)
            "buttons": [],        # list of dicts with coordinate parameters
            "labels": [],         # list of dynamically parsed labels
            "callbacks": {},      # func_name -> target_tile_var (e.g. 'btn_open_clock_cb' -> 'tile_clock')
            "screen_width": 410,
            "screen_height": 502,
        }
        
        if not filepath or not os.path.exists(filepath):
            return config
            
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()

            # Parse physical LCD resolutions
            res_w = re.search(r'#define\s+LCD_H_RES\s+(\d+)', content)
            res_h = re.search(r'#define\s+LCD_V_RES\s+(\d+)', content)
            if res_w: config["screen_width"] = int(res_w.group(1))
            if res_h: config["screen_height"] = int(res_h.group(1))

            # Parse Grid Setup: tile_var = lv_tileview_add_tile(tv, x, y, ...)
            tile_matches = re.finditer(r'(\w+)\s*=\s*lv_tileview_add_tile\(\s*tv\s*,\s*(\d+)\s*,\s*(\d+)\s*', content)
            for m in tile_matches:
                var_name = m.group(1)
                x_idx = int(m.group(2))
                config["tiles"][var_name] = x_idx

            # Parse Click Callbacks: void callback_name(...) { lv_obj_set_tile(tv, target_tile, ...); }
            cb_matches = re.finditer(
                r'void\s+(\w+)\s*\([^)]*\)\s*\{\s*lv_obj_set_tile\(\s*tv\s*,\s*(\w+)\s*,', 
                content
            )
            for m in cb_matches:
                func_name = m.group(1)
                target_tile = m.group(2)
                config["callbacks"][func_name] = target_tile

            # Find all buttons created in launcher: btn_var = lv_button_create(parent_tile_var)
            btn_matches = re.finditer(r'(\w+)\s*=\s*lv_button_create\(\s*(\w+)\s*\)', content)
            buttons_dict = {}
            for m in btn_matches:
                btn_var = m.group(1)
                parent_tile = m.group(2)
                buttons_dict[btn_var] = {
                    "var": btn_var,
                    "parent_tile": parent_tile,
                    "w": 120, "h": 120, # Default layouts
                    "align": "LV_ALIGN_CENTER",
                    "x": 0, "y": 0,
                    "img_src": None,
                    "target_tile_var": None
                }

            # Parse Button Sizes: lv_obj_set_size(btn_var, w, h)
            size_matches = re.finditer(r'lv_obj_set_size\(\s*(\w+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)', content)
            for m in size_matches:
                btn_var = m.group(1)
                if btn_var in buttons_dict:
                    buttons_dict[btn_var]["w"] = int(m.group(2))
                    buttons_dict[btn_var]["h"] = int(m.group(3))

            # Parse Button Alignment: lv_obj_align(btn_var, ALIGN_TYPE, x, y)
            align_matches = re.finditer(
                r'lv_obj_align\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\)', 
                content
            )
            for m in align_matches:
                btn_var = m.group(1)
                if btn_var in buttons_dict:
                    buttons_dict[btn_var]["align"] = m.group(2)
                    buttons_dict[btn_var]["x"] = int(m.group(3))
                    buttons_dict[btn_var]["y"] = int(m.group(4))

            # Parse Event Registration: lv_obj_add_event_cb(btn_var, callback, ...)
            event_matches = re.finditer(
                r'lv_obj_add_event_cb\(\s*(\w+)\s*,\s*(\w+)\s*,\s*LV_EVENT_CLICKED', 
                content
            )
            for m in event_matches:
                btn_var = m.group(1)
                cb_func = m.group(2)
                if btn_var in buttons_dict and cb_func in config["callbacks"]:
                    buttons_dict[btn_var]["target_tile_var"] = config["callbacks"][cb_func]

            # Parse Image bindings inside button container
            img_creation = re.finditer(r'(\w+)\s*=\s*lv_image_create\(\s*(\w+)\s*\)', content)
            img_to_btn = {}
            for m in img_creation:
                img_to_btn[m.group(1)] = m.group(2)

            img_sources = re.finditer(r'lv_image_set_src\(\s*(\w+)\s*,\s*&?(\w+)\s*\)', content)
            for m in img_sources:
                img_var = m.group(1)
                src_var = m.group(2)
                if img_var in img_to_btn:
                    btn_var = img_to_btn[img_var]
                    if btn_var in buttons_dict:
                        if src_var in ("clock_src", "ui_img_clock"):
                            buttons_dict[btn_var]["img_src"] = "clock"
                        elif src_var in ("gear_src", "ui_img_gear"):
                            buttons_dict[btn_var]["img_src"] = "gear"
                        else:
                            buttons_dict[btn_var]["img_src"] = src_var

            # ==================================================================
            # DYNAMIC LABEL DETECTOR ENGINE
            # ==================================================================
            # Find all label declarations: var_name = lv_label_create(parent)
            lbl_matches = re.finditer(r'(\w+)\s*=\s*lv_label_create\(\s*(\w+)\s*\)', content)
            labels_dict = {}
            for m in lbl_matches:
                lbl_var = m.group(1)
                parent_tile = m.group(2)

                # Default Fallback Layout Metrics
                color = "#ffffff"
                align_type = "LV_ALIGN_CENTER"
                x = 0
                y = 0
                width = "auto"
                font_size = 14

                # 1. Parse Text Colors
                make_m = re.search(r'lv_obj_set_style_text_color\(\s*' + lbl_var + r'\s*,\s*lv_color_make\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)\s*', content)
                if make_m:
                    color = f"rgb({make_m.group(1)},{make_m.group(2)},{make_m.group(3)})"
                else:
                    white_m = re.search(r'lv_obj_set_style_text_color\(\s*' + lbl_var + r'\s*,\s*lv_color_white\(\s*\)\s*', content)
                    if white_m:
                        color = "#ffffff"
                    else:
                        black_m = re.search(r'lv_obj_set_style_text_color\(\s*' + lbl_var + r'\s*,\s*lv_color_black\(\s*\)\s*', content)
                        if black_m:
                            color = "#000000"
                        else:
                            hex_m = re.search(r'lv_obj_set_style_text_color\(\s*' + lbl_var + r'\s*,\s*lv_color_hex\(\s*(0x[0-9a-fA-F]+)\s*\)\s*', content)
                            if hex_m:
                                color = hex_m.group(1).replace("0x", "#")

                # 2. Parse Layout Position Alignment & Offsets
                align_m = re.search(r'lv_obj_align\(\s*' + lbl_var + r'\s*,\s*(\w+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\)', content)
                if align_m:
                    align_type = align_m.group(1)
                    x = int(align_m.group(2))
                    y = int(align_m.group(3))

                # 3. Parse Dimensions / Target Widths
                width_m = re.search(r'lv_obj_set_width\(\s*' + lbl_var + r'\s*,\s*(\w+)\s*\)', content)
                if width_m:
                    width_val = width_m.group(1)
                    if width_val == "LCD_H_RES":
                        width = 410
                    elif width_val.isdigit():
                        width = int(width_val)

                # 4. Parse Montserrat Font Height Compile Tags or custom arial_160
                font_m = re.search(r'lv_obj_set_style_text_font\(\s*' + lbl_var + r'\s*,\s*&lv_font_montserrat_(\d+)\s*', content)
                if font_m:
                    font_size = int(font_m.group(1))
                else:
                    if re.search(r'lv_obj_set_style_text_font\(\s*' + lbl_var + r'\s*,\s*&arial_160\s*', content):
                        font_size = 160

                labels_dict[lbl_var] = {
                    "var": lbl_var,
                    "parent_tile": parent_tile,
                    "color": color,
                    "align": align_type,
                    "x": x,
                    "y": y,
                    "width": width,
                    "font_size": font_size
                }

            config["buttons"] = list(buttons_dict.values())
            config["labels"] = list(labels_dict.values())
            
        except Exception as e:
            print(f"Error parsing main.c: {e}")
            
        return config


# ==============================================================================
# 3. TOUCH-SENSITIVE HORIZONTAL TILEVIEW CONTAINER
# ==============================================================================
class TouchTileView(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedSize(410, 502)
        
        self.container = QWidget(self)
        self.container.setGeometry(0, 0, 410 * 3, 502)
        
        self.dragging = False
        self.drag_start_x = 0
        self.container_start_x = 0
        self.current_tile = 1  # Start at Launcher (Tile 1)
        
        self.container.move(-410, 0)
        
        self.anim = QPropertyAnimation(self.container, b"pos")
        self.anim.setDuration(220)
        self.anim.setEasingCurve(QEasingCurve.OutQuad)

    def add_tile(self, widget, index):
        widget.setParent(self.container)
        widget.setGeometry(index * 410, 0, 410, 502)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.anim.stop()
            self.dragging = True
            self.drag_start_x = event.globalPosition().x()
            self.container_start_x = self.container.x()
            event.accept()

    def mouseMoveEvent(self, event):
        if self.dragging:
            dx = event.globalPosition().x() - self.drag_start_x
            new_x = self.container_start_x + dx
            new_x = max(-820, min(0, new_x))
            self.container.move(new_x, 0)
            event.accept()

    def mouseReleaseEvent(self, event):
        if self.dragging:
            self.dragging = False
            target_tile = round(-self.container.x() / 410)
            self.slide_to_tile(target_tile)
            event.accept()

    def slide_to_tile(self, index):
        self.current_tile = index
        self.anim.setStartValue(self.container.pos())
        self.anim.setEndValue(QPoint(-index * 410, 0))
        self.anim.start()


# ==============================================================================
# 4. INTERACTIVE SIMULATOR GUI
# ==============================================================================
class SmartwatchSimulator(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("ESP32-S3 Watch UI Prototype & Asset Simulator")
        self.setFixedSize(980, 640)
        self.setStyleSheet("background-color: #1e1e1e; color: #f0f0f0; font-family: 'Segoe UI', Arial;")

        self.battery_pct = 85
        self.wifi_ssid = ""
        self.wifi_pass = ""
        self.is_connected = False
        self.ap_active = False
        self.dyn_buttons = []
        self.dyn_labels = {}
        self.parsed_config = {"tiles": {}, "buttons": [], "labels": []}

        self.setup_ui()
        self.init_timers()
        self.attempt_auto_load()

    def setup_ui(self):
        main_layout = QHBoxLayout()
        main_layout.setContentsMargins(30, 30, 30, 30)
        main_layout.setSpacing(40)
        
        # --- LEFT SIDE: THE SMARTWATCH HARDWARE FRAME ---
        watch_container = QVBoxLayout()
        watch_container.setAlignment(Qt.AlignCenter)
        
        self.bezel = QFrame()
        self.bezel.setFixedSize(450, 542)
        self.bezel.setStyleSheet("""
            QFrame {
                background-color: #2c2c2c;
                border: 6px solid #4a4a4a;
                border-radius: 42px;
            }
        """)
        bezel_layout = QVBoxLayout(self.bezel)
        bezel_layout.setContentsMargins(14, 14, 14, 14)
        bezel_layout.setAlignment(Qt.AlignCenter)

        self.screen_frame = QFrame()
        self.screen_frame.setFixedSize(410, 502)
        self.screen_frame.setStyleSheet("""
            QFrame {
                background-color: #000000;
                border: 1px solid #111111;
                border-radius: 20px;
            }
        """)
        
        self.tile_view = TouchTileView(self.screen_frame)
        self.create_simulated_tiles()

        bezel_layout.addWidget(self.screen_frame)
        watch_container.addWidget(self.bezel)
        main_layout.addLayout(watch_container)

        # --- RIGHT SIDE: CONTROLS & TELEMETRY MONITOR ---
        panel_layout = QVBoxLayout()
        panel_layout.setSpacing(15)

        # Workspace Importer & Directory Picker
        loader_group = QFrame()
        loader_group.setStyleSheet("background-color: #2a2a2a; border-radius: 8px; padding: 12px;")
        loader_vbox = QVBoxLayout(loader_group)
        loader_vbox.setSpacing(8)
        
        loader_title = QLabel("Workspace Directory Importer")
        loader_title.setStyleSheet("font-weight: bold; font-size: 14px; color: #00bfff;")
        loader_vbox.addWidget(loader_title)

        btn_load_folder = QPushButton("Load Project Workspace...")
        btn_load_folder.setStyleSheet("background-color: #00bfff; color: black; font-weight: bold; padding: 8px; border-radius: 4px;")
        btn_load_folder.clicked.connect(self.select_project_folder)
        loader_vbox.addWidget(btn_load_folder)

        self.lbl_folder_path = QLabel("No workspace loaded")
        self.lbl_folder_path.setStyleSheet("color: #777; font-size: 11px;")
        self.lbl_folder_path.setWordWrap(True)
        loader_vbox.addWidget(self.lbl_folder_path)

        panel_layout.addWidget(loader_group)

        # Telemetry Simulator
        telemetry_group = QFrame()
        telemetry_group.setStyleSheet("background-color: #2a2a2a; border-radius: 8px; padding: 10px;")
        telemetry_vbox = QVBoxLayout(telemetry_group)
        telemetry_vbox.setSpacing(10)

        telemetry_title = QLabel("Watch Telemetry Mock Controls")
        telemetry_title.setStyleSheet("font-weight: bold; font-size: 14px; color: #00bfff;")
        telemetry_vbox.addWidget(telemetry_title)

        bat_lbl_layout = QHBoxLayout()
        bat_lbl_layout.addWidget(QLabel("Battery Level:"))
        self.bat_num_lbl = QLabel("85%")
        self.bat_num_lbl.setAlignment(Qt.AlignRight)
        bat_lbl_layout.addWidget(self.bat_num_lbl)
        telemetry_vbox.addLayout(bat_lbl_layout)

        self.bat_slider = QSlider(Qt.Horizontal)
        self.bat_slider.setRange(0, 100)
        self.bat_slider.setValue(85)
        self.bat_slider.setStyleSheet("QSlider::handle:horizontal { background-color: #00bfff; }")
        self.bat_slider.valueChanged.connect(self.adjust_sim_battery)
        telemetry_vbox.addWidget(self.bat_slider)

        panel_layout.addWidget(telemetry_group)

        # Mock Console Output (ESP-IDF log parser simulation)
        console_group = QFrame()
        console_group.setStyleSheet("background-color: #2a2a2a; border-radius: 8px; padding: 10px;")
        console_vbox = QVBoxLayout(console_group)
        
        console_title = QLabel("ESP-IDF Simulator System Log")
        console_title.setStyleSheet("font-weight: bold; font-size: 14px; color: #00bfff;")
        console_vbox.addWidget(console_title)

        self.log_output = QTextEdit()
        self.log_output.setReadOnly(True)
        self.log_output.setStyleSheet("""
            QTextEdit {
                background-color: #111111;
                color: #39ff14;
                font-family: Consolas, Monaco, monospace;
                font-size: 11px;
                border: 1px solid #333;
                border-radius: 4px;
            }
        """)
        console_vbox.addWidget(self.log_output)
        panel_layout.addWidget(console_group)

        main_layout.addLayout(panel_layout, 1)
        
        central_widget = QWidget()
        central_widget.setLayout(main_layout)
        self.setCentralWidget(central_widget)

        self.log_info("Simulator Boot Complete. Ready.")

    def create_simulated_tiles(self):
        # ==================== TILE 0: CLOCK APP ====================
        self.t_clock = QFrame()
        self.t_clock.setStyleSheet("background-color: black; border-radius: 20px;")

        # ==================== TILE 1: LAUNCHER SCREEN ====================
        self.t_launcher = QFrame()
        self.t_launcher.setStyleSheet("background-color: black; border-radius: 20px;")

        lbl_swipe = QLabel("◄ Swipe  ►", self.t_launcher)
        lbl_swipe.setGeometry(140, 460, 130, 25)
        lbl_swipe.setAlignment(Qt.AlignCenter)
        lbl_swipe.setStyleSheet("color: #555555; font-size: 12px; font-weight: bold; background-color: transparent;")

        # Fallback default static buttons (rebuilt dynamically when workspace imports)
        self.create_default_fallback_buttons()
        self.create_default_fallback_labels()

        # ==================== TILE 2: SETTINGS SCREEN ====================
        self.t_settings = QFrame()
        self.t_settings.setStyleSheet("background-color: black; border-radius: 20px;")
        settings_layout = QVBoxLayout(self.t_settings)
        settings_layout.setContentsMargins(35, 40, 35, 30)
        settings_layout.setSpacing(12)

        lbl_settings_hdr = QLabel("Wi-Fi Setup")
        lbl_settings_hdr.setStyleSheet("color: #00bfff; font-size: 18px; font-weight: bold; background-color: transparent;")
        lbl_settings_hdr.setAlignment(Qt.AlignCenter)
        settings_layout.addWidget(lbl_settings_hdr)

        self.input_ssid = QLineEdit()
        self.input_ssid.setPlaceholderText("WiFi SSID")
        self.input_ssid.setStyleSheet("""
            QLineEdit {
                background-color: #121212;
                border: 1px solid #333;
                border-radius: 4px;
                padding: 8px;
                color: white;
            }
        """)
        settings_layout.addWidget(self.input_ssid)

        self.input_pass = QLineEdit()
        self.input_pass.setPlaceholderText("WiFi Password")
        self.input_pass.setEchoMode(QLineEdit.Password)
        self.input_pass.setStyleSheet("""
            QLineEdit {
                background-color: #121212;
                border: 1px solid #333;
                border-radius: 4px;
                padding: 8px;
                color: white;
            }
        """)
        settings_layout.addWidget(self.input_pass)

        self.btn_sim_conn = QPushButton("Connect")
        self.btn_sim_conn.setStyleSheet("""
            QPushButton {
                background-color: #00bfff;
                color: black;
                font-weight: bold;
                border-radius: 4px;
                padding: 8px;
            }
            QPushButton:hover {
                background-color: #0099dd;
            }
        """)
        self.btn_sim_conn.clicked.connect(self.simulate_wifi_connection)
        settings_layout.addWidget(self.btn_sim_conn)

        self.btn_sim_ap = QPushButton("AP Mode")
        self.btn_sim_ap.setStyleSheet("""
            QPushButton {
                background-color: #333;
                color: white;
                font-weight: bold;
                border-radius: 4px;
                padding: 8px;
            }
            QPushButton:hover {
                background-color: #444;
            }
        """)
        self.btn_sim_ap.clicked.connect(self.simulate_ap_mode)
        settings_layout.addWidget(self.btn_sim_ap)

        self.tile_view.add_tile(self.t_clock, 0)
        self.tile_view.add_tile(self.t_launcher, 1)
        self.tile_view.add_tile(self.t_settings, 2)

    def create_default_fallback_buttons(self):
        # Clear previous dynamic buttons
        for btn in self.dyn_buttons:
            btn.deleteLater()
        self.dyn_buttons.clear()

        # Build Clock button
        btn_clock = QPushButton(self.t_launcher)
        btn_clock.setGeometry(60, 180, 120, 120)
        btn_clock.setStyleSheet("background-color: black; border: 2px solid #222; border-radius: 60px;")
        lbl_clock = QLabel(btn_clock)
        lbl_clock.setGeometry(0, 0, 120, 120)
        lbl_clock.setAlignment(Qt.AlignCenter)
        lbl_clock.setStyleSheet("color: #a0a0a0; font-size: 14px; background-color: transparent;")
        lbl_clock.setText("Clock")
        btn_clock.clicked.connect(lambda: self.tile_view.slide_to_tile(0))
        btn_clock.show()
        self.dyn_buttons.append(btn_clock)

        # Build Settings button
        btn_settings = QPushButton(self.t_launcher)
        btn_settings.setGeometry(230, 180, 120, 120)
        btn_settings.setStyleSheet("background-color: black; border: 2px solid #222; border-radius: 60px;")
        lbl_settings = QLabel(btn_settings)
        lbl_settings.setGeometry(0, 0, 120, 120)
        lbl_settings.setAlignment(Qt.AlignCenter)
        lbl_settings.setStyleSheet("color: #a0a0a0; font-size: 14px; background-color: transparent;")
        lbl_settings.setText("Settings")
        btn_settings.clicked.connect(lambda: self.tile_view.slide_to_tile(2))
        btn_settings.show()
        self.dyn_buttons.append(btn_settings)

    def create_default_fallback_labels(self):
        # Clear previous dynamic labels
        for lbl in self.dyn_labels.values():
            lbl.deleteLater()
        self.dyn_labels.clear()

        # Fallback clock display if no main.c configuration exists
        self.dyn_labels["label_clock_hours"] = QLabel(self.t_clock)
        self.dyn_labels["label_clock_hours"].setGeometry(0, 80, 410, 160)
        self.dyn_labels["label_clock_hours"].setAlignment(Qt.AlignCenter)
        self.dyn_labels["label_clock_hours"].setStyleSheet("color: #0096ff; font-size: 110px; font-weight: bold; background-color: transparent;")
        self.dyn_labels["label_clock_hours"].show()

        self.dyn_labels["label_clock_minutes"] = QLabel(self.t_clock)
        self.dyn_labels["label_clock_minutes"].setGeometry(0, 240, 410, 160)
        self.dyn_labels["label_clock_minutes"].setAlignment(Qt.AlignCenter)
        self.dyn_labels["label_clock_minutes"].setStyleSheet("color: white; font-size: 110px; font-weight: bold; background-color: transparent;")
        self.dyn_labels["label_clock_minutes"].show()

        # Fallback battery display
        self.dyn_labels["lbl_battery"] = QLabel(self.t_launcher)
        self.dyn_labels["lbl_battery"].setGeometry(20, 20, 120, 25)
        self.dyn_labels["lbl_battery"].setStyleSheet("color: #a0a0a0; font-size: 14px; font-weight: bold; background-color: transparent;")
        self.dyn_labels["lbl_battery"].setText(f"Bat: {self.battery_pct}%")
        self.dyn_labels["lbl_battery"].show()

    def init_timers(self):
        self.update_timer = QTimer(self)
        self.update_timer.timeout.connect(self.system_refresh_loop)
        self.update_timer.start(1000)

    # ==============================================================================
    # 4. SIMULATION WORKFLOW & ACTIONS
    # ==============================================================================
    def system_refresh_loop(self):
        # Strip leading zeroes on hours to match the watch's display design
        hour_int = int(time.strftime("%H"))
        hour_str = str(hour_int)
        
        # Minutes display retains double-digit form
        min_str = time.strftime("%M")
        sec_str = time.strftime("%S")

        # Dynamically tick whatever labels were successfully discovered and parsed from main.c
        if "label_clock_hours" in self.dyn_labels:
            self.dyn_labels["label_clock_hours"].setText(hour_str)
        if "label_clock_minutes" in self.dyn_labels:
            self.dyn_labels["label_clock_minutes"].setText(min_str)
        if "label_clock_time" in self.dyn_labels:
            # Revert smoothly to original single-line ticker if user reverts code
            self.dyn_labels["label_clock_time"].setText(f"{hour_str}:{min_str}:{sec_str}")

        # Update telemetry labels dynamically
        if "lbl_battery" in self.dyn_labels:
            self.dyn_labels["lbl_battery"].setText(f"Bat: {self.battery_pct}%")
        if "lbl_wifi" in self.dyn_labels:
            self.dyn_labels["lbl_wifi"].setText("📶" if self.is_connected else "")

    def adjust_sim_battery(self, val):
        self.battery_pct = val
        self.bat_num_lbl.setText(f"{val}%")
        if "lbl_battery" in self.dyn_labels:
            self.dyn_labels["lbl_battery"].setText(f"Bat: {val}%")
        self.log_info(f"Battery Telemetry: V_BAT={3.2 + (val*0.01):.2f}V, {val}%")

    def simulate_wifi_connection(self):
        ssid = self.input_ssid.text()
        if not ssid:
            self.log_warn("Wi-Fi Connection request skipped: Empty SSID.")
            return

        self.ap_active = False
        self.btn_sim_ap.setText("AP Mode")
        self.btn_sim_ap.setStyleSheet("background-color: #333; color: white; padding: 8px;")

        self.log_info(f"Connecting to SSID: {ssid}")
        self.btn_sim_conn.setText("Connecting...")
        self.btn_sim_conn.setEnabled(False)

        QTimer.singleShot(1500, lambda: self.complete_mock_connection(ssid))

    def complete_mock_connection(self, ssid):
        self.is_connected = True
        self.btn_sim_conn.setText("Connected ✓")
        self.btn_sim_conn.setEnabled(True)
        self.btn_sim_conn.setStyleSheet("background-color: #4CAF50; color: white; font-weight: bold; padding: 8px;")
        
        self.log_info(f"Connected! IP Address: 192.168.1.{100 + int(time.time())%100}")
        self.log_info("Initializing SNTP protocol Client...")
        self.log_info("SNTP: pool.ntp.org successfully synchronized.")

    def simulate_ap_mode(self):
        self.is_connected = False
        self.btn_sim_conn.setText("Connect")
        self.btn_sim_conn.setStyleSheet("background-color: #00bfff; color: black; font-weight: bold; padding: 8px;")

        if not self.ap_active:
            self.ap_active = True
            self.btn_sim_ap.setText("AP Mode: Active")
            self.btn_sim_ap.setStyleSheet("background-color: #4CAF50; color: white; font-weight: bold; padding: 8px;")
            self.log_info("Starting AP Mode...")
            self.log_info("AP Mode Active: SSID='Smartwatch_AP' Key='12345678'")
        else:
            self.ap_active = False
            self.btn_sim_ap.setText("AP Mode")
            self.btn_sim_ap.setStyleSheet("background-color: #333; color: white; padding: 8px;")
            self.log_info("Stopped AP Mode.")

    # ==============================================================================
    # 5. RECURSIVE FOLDER WORKSPACE LOADER WITH MAIN.C COORDINATE INGEST
    # ==============================================================================
    def select_project_folder(self):
        folder = QFileDialog.getExistingDirectory(self, "Select Root Project Folder")
        if folder:
            self.load_workspace(folder)

    def load_workspace(self, folder):
        self.lbl_folder_path.setText(os.path.basename(folder))
        self.log_info(f"Scanning project directory: '{folder}'")
        
        main_c_path = None
        clock_path = None
        gear_path = None
        
        for root, dirs, files in os.walk(folder):
            for file in files:
                full_path = os.path.join(root, file)
                if file.lower() == "main.c":
                    main_c_path = full_path
                elif file.lower() == "clock.c":
                    clock_path = full_path
                elif file.lower() == "gear.c":
                    gear_path = full_path

        # 1. Parse Image Assets
        if clock_path:
            self.log_info(f"Parsing clock asset: {os.path.basename(clock_path)}")
            self.pix_clock = LVGLImageParser.parse_file(clock_path)
        else:
            self.log_warn("Could not find 'clock.c' in selected folder.")
            if hasattr(self, 'pix_clock'): delattr(self, 'pix_clock')

        if gear_path:
            self.log_info(f"Parsing settings gear asset: {os.path.basename(gear_path)}")
            self.pix_gear = LVGLImageParser.parse_file(gear_path)
        else:
            self.log_warn("Could not find 'gear.c' in selected folder.")
            if hasattr(self, 'pix_gear'): delattr(self, 'pix_gear')

        # 2. Parse main.c coordinates, layouts, and style scales
        if main_c_path:
            self.log_info(f"Parsing main.c configuration: {os.path.basename(main_c_path)}")
            self.parsed_config = MainCParser.parse_main_c(main_c_path)
        else:
            self.log_warn("Could not find 'main.c' in folder. Falling back to default layout.")
            self.parsed_config = {"tiles": {}, "buttons": [], "labels": []}

        # 4. Dynamic layouts and label reconstructions
        self.rebuild_dynamic_labels()
        self.rebuild_dynamic_launcher()

        # 5. Save to config file (Persist folder choice)
        self.save_workspace_path(folder)

    def get_parent_qframe(self, c_parent):
        if "clock" in c_parent:
            return self.t_clock
        elif "launcher" in c_parent:
            return self.t_launcher
        elif "settings" in c_parent:
            return self.t_settings
        return None

    def rebuild_dynamic_labels(self):
        """
        Dynamically instantiates and aligns QLabel components parsed from main.c.
        """
        for lbl in self.dyn_labels.values():
            lbl.deleteLater()
        self.dyn_labels.clear()

        labels_config = self.parsed_config.get("labels", [])
        if not labels_config:
            self.create_default_fallback_labels()
            return

        for l_conf in labels_config:
            parent_frame = self.get_parent_qframe(l_conf["parent_tile"])
            if not parent_frame:
                continue

            var_name = l_conf["var"]
            lbl = QLabel(parent_frame)

            w = l_conf["width"]
            if w == "auto":
                w = 410
            
            font_size = l_conf["font_size"]
            scale_factor = 1.0

            # Scale up big fonts to high-resolution assets to keep readable on desktop simulator
            if font_size >= 48:
                original_font_size = font_size
                font_size = 160  # Make it massive to fill up the screen
                scale_factor = font_size / original_font_size

            # Map proportionate height bounds using final font size to avoid vertical boundary truncation
            h = int(font_size * 1.15)
            
            align = l_conf["align"]
            dx = int(l_conf["x"] * scale_factor)
            dy = int(l_conf["y"] * scale_factor)

            x, y = self.calculate_coordinates(410, 502, w, h, align, dx, dy)
            lbl.setGeometry(x, y, w, h)
            lbl.setAlignment(Qt.AlignCenter)

            color_style = l_conf["color"]

            lbl.setStyleSheet(f"""
                QLabel {{
                    color: {color_style};
                    font-size: {font_size}px;
                    font-weight: bold;
                    background-color: transparent;
                    font-family: 'Segoe UI', Arial;
                }}
            """)
            lbl.show()
            self.dyn_labels[var_name] = lbl

    def rebuild_dynamic_launcher(self):
        """
        Dynamically renders launcher buttons based on parsed layout coordinates from main.c.
        """
        for btn in self.dyn_buttons:
            btn.deleteLater()
        self.dyn_buttons.clear()

        buttons_config = self.parsed_config.get("buttons", [])
        if not buttons_config:
            self.create_default_fallback_buttons()
            return

        for b_conf in buttons_config:
            # Only render buttons targeted to our launcher screen
            if b_conf.get("parent_tile") != "tile_launcher":
                continue

            btn = QPushButton(self.t_launcher)
            w = b_conf["w"]
            h = b_conf["h"]
            align = b_conf["align"]
            dx = b_conf["x"]
            dy = b_conf["y"]
            
            x, y = self.calculate_coordinates(410, 502, w, h, align, dx, dy)
            btn.setGeometry(x, y, w, h)
            
            # Form clean circles for circular watch icons
            r_border = w // 2
            btn.setStyleSheet(f"""
                QPushButton {{
                    background-color: black;
                    border: 2px solid #222;
                    border-radius: {r_border}px;
                }}
                QPushButton:hover {{
                    border-color: #00bfff;
                }}
            """)
            
            lbl = QLabel(btn)
            lbl.setGeometry(0, 0, w, h)
            lbl.setAlignment(Qt.AlignCenter)
            lbl.setStyleSheet("color: #a0a0a0; font-size: 14px; background-color: transparent;")
            
            img_src_key = b_conf.get("img_src")
            loaded_pixmap = None
            if img_src_key == "clock" and hasattr(self, 'pix_clock'):
                loaded_pixmap = self.pix_clock
            elif img_src_key == "gear" and hasattr(self, 'pix_gear'):
                loaded_pixmap = self.pix_gear

            if loaded_pixmap:
                # Scale parsed pixel-map to button container bounds with a 14px spacing margin
                scaled_pix = loaded_pixmap.scaled(w - 14, h - 14, Qt.KeepAspectRatio, Qt.SmoothTransformation)
                lbl.setPixmap(scaled_pix)
            else:
                # Fallback to readable label if asset parsing failed
                btn_name = b_conf["var"].replace("btn_", "").capitalize()
                lbl.setText(btn_name)

            # Bind active clicks to parsed layout slides
            target_var = b_conf.get("target_tile_var")
            if target_var in self.parsed_config["tiles"]:
                target_idx = self.parsed_config["tiles"][target_var]
                btn.clicked.connect(lambda _, idx=target_idx: self.tile_view.slide_to_tile(idx))

            btn.show()
            self.dyn_buttons.append(btn)

    def calculate_coordinates(self, parent_w, parent_h, w, h, align, dx, dy):
        """
        Translates standard LVGL align flags into standard PySide coordinates.
        """
        if align == "LV_ALIGN_TOP_LEFT":
            return dx, dy
        elif align == "LV_ALIGN_TOP_MID":
            return (parent_w - w) // 2 + dx, dy
        elif align == "LV_ALIGN_TOP_RIGHT":
            return parent_w - w + dx, dy
        elif align == "LV_ALIGN_BOTTOM_LEFT":
            return dx, parent_h - h + dy
        elif align == "LV_ALIGN_BOTTOM_MID":
            return (parent_w - w) // 2 + dx, parent_h - h + dy
        elif align == "LV_ALIGN_BOTTOM_RIGHT":
            return parent_w - w + dx, parent_h - h + dy
        else: # Default or LV_ALIGN_CENTER
            return (parent_w - w) // 2 + dx, (parent_h - h) // 2 + dy

    # Persist folder selection via JSON
    def save_workspace_path(self, folder):
        try:
            with open(CONFIG_FILE, 'w') as f:
                json.dump({"last_workspace": folder}, f, indent=4)
        except Exception as e:
            self.log_warn(f"Failed to save simulator configuration: {e}")

    def attempt_auto_load(self):
        """
        Autoloads the last folder workspace specified inside 'simulator_config.json'.
        """
        if os.path.exists(CONFIG_FILE):
            try:
                with open(CONFIG_FILE, 'r') as f:
                    data = json.load(f)
                    last_ws = data.get("last_workspace")
                    if last_ws and os.path.exists(last_ws):
                        self.load_workspace(last_ws)
                        return
            except Exception as e:
                self.log_warn(f"Failed to read simulator config: {e}")
        
        # Fallback to local scans if JSON config is missing
        base_dir = os.path.dirname(os.path.abspath(__file__))
        
        fallback_dirs = [
            os.path.join(base_dir, "Smartwatch_OS"),
            base_dir,
            os.path.join(base_dir, "..", "Smartwatch_OS")
        ]

        for d in fallback_dirs:
            if os.path.exists(d):
                # Search inside the directory to confirm it's actually the project
                for root, dirs, files in os.walk(d):
                    if "main.c" in files or "clock.c" in files:
                        self.load_workspace(d)
                        return

    # Logging Utilities
    def log_info(self, msg):
        self.log_output.append(f"<span style='color:#a0a0a0;'>[I] ({int(time.time() * 1000) % 100000}) SmartwatchOS:</span> {msg}")
    
    def log_warn(self, msg):
        self.log_output.append(f"<span style='color:#ffaa00;'>[W] ({int(time.time() * 1000) % 100000}) SmartwatchOS:</span> {msg}")

    def log_err(self, msg):
        self.log_output.append(f"<span style='color:#ff3333;'>[E] ({int(time.time() * 1000) % 100000}) SmartwatchOS:</span> {msg}")


# ==============================================================================
# 6. RUNTIME ENTRYPOINT
# ==============================================================================
if __name__ == "__main__":
    app = QApplication(sys.argv)
    sim = SmartwatchSimulator()
    sim.show()
    sys.exit(app.exec())